spring:
  application:
    name: auth-service

  datasource:
    url: ${POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      database: ${REDIS_DATABASE_NUMBER}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: "kafka:9092"
    consumer:
      group-id: "auth-service"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    instance:
      preferIpAddress: true

app:
  jwt:
    subject: ${JWT_SUBJECT}
    issuer: ${JWT_ISSUER}
    access:
      duration: ${JWT_ACCESS_DURATION}
      secret: ${JWT_ACCESS_SECRET}
    refresh:
      duration: ${JWT_REFRESH_DURATION}
      secret: ${JWT_REFRESH_SECRET}
  uuid:
    seed: ${UUID_SEED}