name: Build image and deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'v-')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/heads/}
          echo "Extracted version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.6

      - name: check java version
        run: |
          java -version
          mvn --version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "$PATH"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.version }}