name: Auth Service CI/CD Pipeline

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.6

      - name: Check Java version
        run: |
          java -version
          mvn --version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "$PATH"

      - name: Lint with Checkstyle
        run: |
          mvn checkstyle:check
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.6

      - name: Check Java version
        run: |
          java -version
          mvn --version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "$PATH"

      - name: Run tests
        run: |
          mvn clean test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.6

      - name: Check Java version
        run: |
          java -version
          mvn --version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "$PATH"

  test-environtment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Start postgres
        run: |
          docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=app -d postgres
      - name: Start app
        run: |
          mvn package -DskipTests
          docker build -t app .

      - name: Run app
        run: |
          docker run --name app -p 8080:8080 -d app -e POSTGRES_URI=jdbc:postgresql://localhost:5432/app -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres
      - name: Curl actuator
        run: |
          sleep 40
          curl -X GET http://localhost:8080/actuator/health
