name: Auth Service CI/CD Pipeline

on:
  pull_request:

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Give permissions
        run: chmod +x ./mvnw

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

  lint:
    runs-on: ubuntu-latest
    needs: setup_environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint with Checkstyle
        run: |
          ./mvnw checkstyle:check

  test:
    runs-on: ubuntu-latest
    needs: lint
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          mvnw test

  build:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: |
          mvnw clean package -DskipTests

  push_to_docker:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push re-tail/${{ github.event.repository.name }}:${{ github.sha }}