name: Auth Service CI/CD Pipeline

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.6

      - name: Check Java version
        run: |
          java -version
          mvn --version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "$PATH"

      - name: Lint with Checkstyle
        run: |
          mvn checkstyle:check
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.6

      - name: Check Java version
        run: |
          java -version
          mvn --version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "$PATH"

      - name: Run tests
        run: |
          mvn clean test

  build-and-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.6

      - name: Check Java version
        run: |
          java -version
          mvn --version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "$PATH"


      - name: Build with Maven
        run: |
          mvn clean package -DskipTests
      - name: Start
        run: |
          java -jar target/auth-service-0.0.1-SNAPSHOT.jar
      - name: Curl
        run: |
          curl -X GET http://localhost:8080/actuator/health